version: '3.7'
services:
 
  traefik-app:
    image: tiredofit/traefik:2.2-latest
    container_name: traefik-app
    environment:
      - CONTAINER_NAME=traefik-app

      - LETSENCRYPT_EMAIL=homelab@reuchle.eu
      - LETSENCRYPT_CHALLENGE=DNS
      - LETSENCRYPT_DNS_PROVIDER=cloudflare

#      - CF_API_EMAIL=homelab@reuchle.eu
#      - CF_API_KEY=randomapikeyfromcloudflare

      - DASHBOARD_HOSTNAME=uwe-srv-trfk.local
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/lib/docker/volumes/traeffik_config/_data:/traefik/config
      - /var/lib/docker/volumes/traeffik_logs/_data:/traefik/logs
      - /var/lib/docker/volumes/traeffik_certs/_data:/traefik/certs
      networks:
      - proxy
    restart: always

  whoami:
    container_name: whoami
    image: containous/whoami:v1.3.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.example.com`) || Host(`whoami2.example.com`) 
      - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
